systemDictionary = {
    "MegaD Name:":          {"en": "MegaD Name:",           "de": "MegaD Name:",                "ru": "MegaD Имя:"},
    "ioBroker Web Port:":   {"en": "ioBroker Web Port:",    "de": "ioBroker Web Port:",         "ru": "ioBroker веб-порт:"},
    "Poll interval (sec):": {"en": "Poll interval (sec):",  "de": "Abfrage Intervall (sek):",   "ru": "Интервал опроса (сек):"},
    "MegaD Password:":      {"en": "MegaD Password:",       "de": "MegaD Kennword:",            "ru": "MegaD Пароль:"},
    "name":                 {"en": "Name",                  "de": "Name",                       "ru": "Имя"},
    "input":                {"en": "Input",                 "de": "Eingang",                    "ru": "Вход"},
    "switch":               {"en": "Switch",                "de": "Schalter",                   "ru": "Переключатель"},
    "SW LINK":              {"en": "Switch in the group",   "de": "Schalter In der Gruppe",     "ru": "Перекл. в группе"},
    "offset":               {"en": "Offset",                "de": "Offset",                     "ru": "Сдвиг"},
    "factor":               {"en": "Factor",                "de": "Factor",                     "ru": "Множитель"},
    "digital":              {"en": "Digital",               "de": "Digital",                    "ru": "Цифровой"},
    "long":                 {"en": "Long press",            "de": "Long press",                 "ru": "Удержание"},
    "double":               {"en": "Double click ms",       "de": "Double click ms",            "ru": "Двойное нажатие"},
    "Ports":                {"en": "Ports",                 "de": "Ports",                      "ru": "Порты"},
    "Long press detect (ms):": {"en": "Long press detection (ms):", "de": "Langes-Drucken-Erkennung (ms):", "ru": "Интервал для длинного нажатия (мс):"},
    "MegaD-2561 adapter settings": {"en": "MegaD-2561 adapter settings", "de": "MegaD-2561 Adaptereinstellungen", "ru": "MegaD-2561 настройки"},
    "IP:":                  {"en": "MegaD IP:",             "de": "MegaD IP:",                  "ru": "IP Адрес устройства:"},
    "Double press detect (ms):": {"en": "Double press detect (ms):", "de": "Doppelclick-Interval(ms):", "ru": "Интервал двойного нажатия (мс):"},
    "Current firmware version:": {"en": "Current Firmware version:", "de": "Aktuelle Firmware version:", "ru": "Текущая версия прошивки:"},
    "Last known firmware version:": {"en": "Last known Firmware version:", "de": "Letzte bekannte Firmware version:", "ru": "Доступная версия прошивки:"},
    "Add new port":         {"en": "Add new port",          "de": "Neuer Port",                 "ru": "Добавить порт"},
    "Auto detect ports":    {"en": "Auto detect ports",     "de": "Auto-Detekt die Ports",      "ru": "Считать настройки с MegaD"},
    "Write config to device": {"en": "Write config to device", "de": "Konfiguration in das Gerät schreiben", "ru": "Записать настройки в устройство"},
    "Update Firmware":      {"en": "Update Firmware",       "de": "Firmware aktualisieren",     "ru": "Перепрошить MegaD"},
    "Select firmware version": {"en": "Select firmware version", "de": "Firmware version auswählen", "ru": "Выбор версии прошивки"},
    "Firmware updated":     {"en": "Firmware updated",      "de": "Firmware aktualisiert",      "ru": "MegaD перепрошит"},
    "Firmware version":     {"en": "Firmware version",      "de": "Firmware version",           "ru": "Версия прошивки"},
    "Date and time":        {"en": "Date and time",         "de": "Datum und uhrzeit",          "ru": "Дата и время"},
    "Description":          {"en": "Description",           "de": "Beschreibung",               "ru": "Описание"},
    "Firmware":             {"en": "Firmware",              "de": "Firmware",                   "ru": "Прошивка"},
    "Flash":                {"en": "Flash",                 "de": "Flash",                      "ru": "Прошить"},
    "Emergency flashing":   {"en": "Emergency flashing",    "de": "Notfall blinkend",           "ru": "Аварийная перепрошивка"},
    "Refresh with the latest version": {"en": "Refresh with the latest version", "de": "Blitzen die neueste Version", "ru": "Перепрошить последней версией"},
    "Name":                 {"en": "Name",                  "de": "Name",                       "ru": "Имя"},
    "Room":                 {"en": "Room",                  "de": "Zimmer",                     "ru": "Комната"},
    "Role":                 {"en": "Role",                  "de": "Rolle",                      "ru": "Роль"},
    "Type":                 {"en": "Type",                  "de": "Typ",                        "ru": "Тип"},
    "Mode":                 {"en": "Mode",                  "de": "Modus",                      "ru": "Режим"},
    "NC":                   {"en": "Not configured",        "de": "nicht benutzt",              "ru": "не используется"},
    "Input":                {"en": "Input",                 "de": "Input",                      "ru": "Циф. вход"},
    "Output":               {"en": "Output",                "de": "Output",                     "ru": "Циф. выход"},
    "ADC":                  {"en": "Analog in (ADC)",       "de": "Analog in (ADC)",            "ru": "Ан. вход (ADC)"},
    "Digital Sensor":       {"en": "Digital Sensor",        "de": "Digital Sensor",             "ru": "Циф. датчик"},
    "I2C Bus":              {"en": "I2C Bus",               "de": "I2C Bus",                    "ru": "Шина I2C"},
    "normal opened":        {"en": "normal opened",         "de": "bei schliessen",             "ru": "при замыкании"},
    "on change":            {"en": "on change",             "de": "auf änderung",               "ru": "при изменении"},
    "normal closed":        {"en": "normal closed",         "de": "bei auf",                    "ru": "при размыкании"},
    "click mode":           {"en": "click mode",            "de": "presse modus",               "ru": "режим нажатия"},
    "Action:":              {"en": "Action:",               "de": "Aktion:",                    "ru": "Сценарий:"},
    "Net:":                 {"en": "Net:",                  "de": "Net:",                       "ru": "Сетевой сценарий:"},
    "Long:":                {"en": "Long:",                 "de": "Lang-Click:",                "ru": "Долгое нажатие:"},
    "Double:":              {"en": "Double:",               "de": "Double-Click:",              "ru": "Двойное нажатие:"},
    "SCL:":                 {"en": "SCL port:",             "de": "SCL port:",                  "ru": "SCL порт:"},
    "Display:":             {"en": "Display port:",         "de": "Anzeigen port:",             "ru": "Дисплей порт:"},
    "Bright:":              {"en": "Bright:",               "de": "Helligkeit:",                "ru": "Яркость:"},
    "INT:":                 {"en": "INT port:",             "de": "INT port:",                  "ru": "INT порт:"},
    "IN/OUT:":              {"en": "IN/OUT:",               "de": "IN/OUT:",                    "ru": "IN/OUT:"},
    "Group:":               {"en": "Group index:",          "de": "Konzernindex:",              "ru": "Групповой индекс:"},
    "not monitored":        {"en": "not monitored",         "de": "nicht beobachtet",           "ru": "не наблюдать"},
    "> threshold":          {"en": "> threshold",           "de": "> Schwellwert",              "ru": "> порога"},
    "< threshold":          {"en": "< threshold",           "de": "< Schwellwert",              "ru": "< порога"},
    "<> threshold":         {"en": "<> threshold",          "de": "<> Schwellwert",             "ru": "<> порога"},
    "Offset:":              {"en": "Offset:",               "de": "Offset:",                    "ru": "Сдвиг:"},
    "Factor:":              {"en": "Factor:",               "de": "Faktor:",                    "ru": "Множитель:"},
    "DHT11":                {"en": "DHT11",                 "de": "DHT11",                      "ru": "DHT11"},
    "DHT22":                {"en": "DHT22",                 "de": "DHT22",                      "ru": "DHT22"},
    "PWM":                  {"en": "PWM",                   "de": "PWM",                        "ru": "ШИМ"},
    "DS2413":               {"en": "DS2413",                "de": "DS2413",                     "ru": "DS2413"},
    "HTU21D":               {"en": "HTU21D",                "de": "HTU21D",                     "ru": "HTU21D"},
    "BMP180":               {"en": "BMP180",                "de": "BMP180",                     "ru": "BMP180"},
    "BMx280":               {"en": "BMx280",                "de": "BMx280",                     "ru": "BMx280"},
    "MAX44009":             {"en": "MAX44009",              "de": "MAX44009",                   "ru": "MAX44009"},
    "BH1750":               {"en": "BH1750",                "de": "BH1750",                     "ru": "BH1750"},
    "TSL2591":              {"en": "TSL2591",               "de": "TSL2591",                    "ru": "TSL2591"},
    "SSD1306":              {"en": "SSD1306",               "de": "SSD1306",                    "ru": "SSD1306"},
    "MCP230XX":             {"en": "MCP230XX",              "de": "MCP230XX",                   "ru": "MCP230XX"},
    "PCA9685":              {"en": "PCA9685",               "de": "PCA9685",                    "ru": "PCA9685"},
    "ANY":                  {"en": "Any",                   "de": "Alle",                       "ru": "Любой"},
    "Scan":                 {"en": "Scan",                  "de": "Scan",                       "ru": "Поиск"},
    "SDA":                  {"en": "SDA",                   "de": "SDA",                        "ru": "SDA"},
    "SCL":                  {"en": "SCL",                   "de": "SCL",                        "ru": "SCL"},
    "Frequency:":           {"en": "Frequency:",            "de": "Frequenz:",                  "ru": "Частота:"},
    "Default state:":       {"en": "Default state:",        "de": "Default Zustand:",           "ru": "По умолчанию:"},
    "off":                  {"en": "off",                   "de": "off",                        "ru": "выкл"},
    "on":                   {"en": "on",                    "de": "on",                         "ru": "вкл"},
    "Norm":                 {"en": "Norm",                  "de": "Norm",                       "ru": "Норма"},
    "Low":                  {"en": "Low",                   "de": "Niedrig",                    "ru": "Низкая"},
    "High":                 {"en": "High",                  "de": "Hoch",                       "ru": "Высокая"},
    "D0":                   {"en": "D0",                    "de": "D0",                         "ru": "D0"},
    "D1":                   {"en": "D1",                    "de": "D1",                         "ru": "D1"},
    "Threshold:":           {"en": "Threshold:",            "de": "Schwellwert:",               "ru": "Порог:"},
    "Hysteresis:":          {"en": "Hysteresis:",           "de": "Hysterese:",                 "ru": "Гистерезис:"},
    "Smooth:":              {"en": "Smooth:",               "de": "Glatt:",                     "ru": "Плавный:"},
    "Misc:":                {"en": "Misc:",                 "de": "Misc:",                      "ru": "Misc:"},
    "D1:":                  {"en": "D1 port:",              "de": "D1 port:",                   "ru": "D1 порт:"},
    "Change ip or password": {
        "en": "Change ip or password",
        "de": "IP Adresse oder Kennwort ändern",
        "ru": "Изменить IP или пароль"
    },
    "Take new settings into config:": {
        "en": "Take new settings into config:",
        "de": "Neue Einstellungen übernehmen:",
        "ru": "Перенять новые настройки:"
    },
    "Old IP:":             {"en": "Old IP:",               "de": "Alte IP:",                   "ru": "Старый IP:"},
    "Old password:":       {"en": "Old password:",         "de": "Altes Kennwort:",            "ru": "Старый пароль:"},
    "New IP:":             {"en": "New IP:",               "de": "Neue IP:",                   "ru": "Новый IP:"},
    "New password:":       {"en": "New password:",         "de": "Neues Kennwort:",            "ru": "Новый пароль:"},
    "Set new password or IP address": {
        "en": "Set new password or IP address",
        "de": "Set new password or IP address",
        "ru": "Изменить IP или пароль на устройстве"
    },
    "Nothing changed": {
        "en": "Nothing changed",
        "de": "Nichts hat sich geändert",
        "ru": "Ничего не изменилось"
    },
    "Ok":                   {"en": "Ok",                    "de": "Ok",                         "ru": "Ok"},
    "Cancel":               {"en": "Cancel",                "de": "Abrechen",                   "ru": "Отмена"},
    "Error":                {"en": "Error",                 "de": "Fehler",                     "ru": "Ошибка"},
    "Find devices":         {"en": "Find devices",          "de": "Suche Geräte",               "ru": "Искать устройства"},
    "Enable adapter first": {
        "en": "Enable adapter first",
        "de": "Aktivieren sie zuerst den adapter",
        "ru": "Сперва включите адаптер"
    },
    "Nothing found":        {"en": "Nothing found",         "de": "Nichts gefunden",            "ru": "Ничего не найдено"},
    "Information will be merged. Are you sure?": {
        "en": "Information will be merged. Are you sure?",
        "de": "Informationen werden zusammengeführt. Bist du sicher?",
        "ru": "Информация будет объединена. Вы уверены?"
    },
    "Firmware will be rewrited. All config will be lost. Are you sure?": {
        "en": "Firmware will be rewrited. All config will be lost. Are you sure?",
        "de": "Firmware wird umgeschrieben. Alle config wird verloren gehen. Bist du sicher?",
        "ru": "Микропрограмма будет перезаписана. Все настройки будут потеряны. Вы уверены?"
    },
    "PWM:":                 {"en": "PWM:",                  "de": "PWM:",                       "ru": "PWM:"},
    "Sensor type:":         {"en": "Sensor type:",          "de": "Sensortyp:",                 "ru": "Тип сенсора:"},
    "De-bounce:":           {"en": "De-bounce:",            "de": "Entprellen:",                "ru": "Дребезг:"}
};    
